#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event6 c 13 70"
export BOOTREC_EVENT="/dev/input/event6"
export BOOTREC_CACHE_NODE="/dev/block/mmcblk0p20 b 179 20"
export BOOTREC_CACHE="/dev/block/mmcblk0p20"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p16 b 179 16"
export BOOTREC_FOTA="/dev/block/mmcblk0p16"
